### ISSUE TITLE
PHP 7.2+ - mcrypt_encrypt is deprecated and removed

### ISSUE THREAD

**Issue by francwalter** [havet/AESCrypt-PHP#3]
Since PHP 7.2 the function [mcrypt_encrypt](https://www.php.net/manual/de/function.mcrypt-encrypt.php) is removed and the example throws errors in PHP.
It should be replace with actual openssl_... functions, but maybe not that easy possible.
I dont see a quick fix here.

**Comment by havet** [comment]
Many thanks to Tunedal for solving this issue rapidly.

**Comment by francwalter** [comment]
Many thanks for fixing it and also many thanks for merging it so quickly :)
